// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
	name: "Elements",
	platforms: [
		.iOS("26.0"),
	],
	products: [
		.iOSApplication(
			name: "Elements",
			targets: ["AppModule"],
			bundleIdentifier: "com.omeriadon.dev.Elements",
			teamIdentifier: "C2HN547N49",
			displayVersion: "1.0",
			bundleVersion: "1",
			appIcon: .asset("AppIcon"),
			accentColor: .asset("AccentColor"),
			supportedDeviceFamilies: [
				.phone,
			],
			supportedInterfaceOrientations: [
				.portrait,
			],
			appCategory: .education
		),
	],
	targets: [
		.executableTarget(
			name: "AppModule",
			path: ".",
			resources: [
				.process("Resources"),
			]
		),
	],
	swiftLanguageVersions: [.v5]
)
