// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
	name: "Elements",
	platforms: [
		.iOS("26.0"),
	],
	products: [
		.iOSApplication(
			name: "Elements",
			targets: ["AppModule"],
			bundleIdentifier: "com.omeriadon.dev.Elements",
			teamIdentifier: "C2HN547N49",
			displayVersion: "1.1",
			bundleVersion: "1",
			appIcon: .asset("AppIcon"),
			accentColor: .asset("AccentColor"),
			supportedDeviceFamilies: [
				.pad,
				.phone,
			],
			supportedInterfaceOrientations: [
				.portrait,
				.landscapeRight,
				.landscapeLeft,
				.portraitUpsideDown(.when(deviceFamilies: [.pad])),
			],
			appCategory: .education
		),
	],
	dependencies: [
		.package(url: "https://github.com/Lakr233/ColorfulX.git", "6.0.1" ..< "7.0.0"),
	],
	targets: [
		.executableTarget(
			name: "AppModule",
			dependencies: [
				.product(name: "ColorfulX", package: "colorfulx"),
			],
			path: ".",
			resources: [
				.process("Resources"),
			]
		),
	]
)
