//
//  PeriodicTableData.swift
//  Elements
//
//  Created by Adon Omeri on 7/11/2025.
//

import Foundation

let elementsString = """
[
 {
  "name": "Hydrogen",
  "appearance": "colorless gas",
  "atomic_mass": 1.008,
  "boil": 20.271,
  "category": "nonmetal",
  "number": 1,
  "period": 1,
  "group": 1,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Hydrogen",
  "summary": "Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.",
  "symbol": "H",
  "xpos": 1,
  "ypos": 1,
  "wxpos": 1,
  "wypos": 1,
  "shells": [1]
 },
 {
  "name": "Helium",
  "appearance": "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
  "atomic_mass": 4.0026022,
  "boil": 4.222,
  "category": "noble gas",
  "number": 2,
  "period": 1,
  "group": 18,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Helium",
  "summary": "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest among all the elements.",
  "symbol": "He",
  "xpos": 18,
  "ypos": 1,
  "wxpos": 32,
  "wypos": 1,
  "shells": [2]
 },
 {
  "name": "Lithium",
  "appearance": "silvery-white",
  "atomic_mass": 6.94,
  "boil": 1603,
  "category": "alkali metal",
  "number": 3,
  "period": 2,
  "group": 1,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Lithium",
  "summary": "Lithium is a chemical element with the symbol Li and atomic number 3. It is a soft, silver-white metal belonging to the alkali metal group of chemical elements. Under standard conditions it is the lightest metal and the least dense solid element.",
  "symbol": "Li",
  "xpos": 1,
  "ypos": 2,
  "wxpos": 1,
  "wypos": 2,
  "shells": [2, 1]
 },
 {
  "name": "Beryllium",
  "appearance": "white-gray metallic",
  "atomic_mass": 9.01218315,
  "boil": 2742,
  "category": "alkaline earth metal",
  "number": 4,
  "period": 2,
  "group": 2,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Beryllium",
  "summary": "Beryllium is a chemical element with symbol Be and atomic number 4. It is created through stellar nucleosynthesis and is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements in minerals.",
  "symbol": "Be",
  "xpos": 2,
  "ypos": 2,
  "wxpos": 2,
  "wypos": 2,
  "shells": [2, 2]
 },
 {
  "name": "Boron",
  "appearance": "black-brown",
  "atomic_mass": 10.81,
  "boil": 4200,
  "category": "metalloid",
  "number": 5,
  "period": 2,
  "group": 13,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Boron",
  "summary": "Boron is a metalloid chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in both the Solar system and the Earth's crust. Boron is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals.",
  "symbol": "B",
  "xpos": 13,
  "ypos": 2,
  "wxpos": 27,
  "wypos": 2,
  "shells": [2, 3]
 },
 {
  "name": "Carbon",
  "appearance": null,
  "atomic_mass": 12.011,
  "boil": null,
  "category": "nonmetal",
  "number": 6,
  "period": 2,
  "group": 14,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Carbon",
  "summary": "Carbon is a chemical element with symbol C and atomic number 6. On the periodic table, it is the first (row 2) of six elements in column (group) 14, which have in common the composition of their outer electron shell. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
  "symbol": "C",
  "xpos": 14,
  "ypos": 2,
  "wxpos": 28,
  "wypos": 2,
  "shells": [2, 4]
 },
 {
  "name": "Nitrogen",
  "appearance": "colorless gas, liquid or solid",
  "atomic_mass": 14.007,
  "boil": 77.355,
  "category": "nonmetal",
  "number": 7,
  "period": 2,
  "group": 15,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Nitrogen",
  "summary": "Nitrogen is a chemical element with symbol N and atomic number 7. It is the lightest pnictogen and at room temperature, it is a transparent, odorless diatomic gas. Nitrogen is a common element in the universe, estimated at about seventh in total abundance in the Milky Way and the Solar System.",
  "symbol": "N",
  "xpos": 15,
  "ypos": 2,
  "wxpos": 29,
  "wypos": 2,
  "shells": [2, 5]
 },
 {
  "name": "Oxygen",
  "appearance": null,
  "atomic_mass": 15.999,
  "boil": 90.188,
  "category": "nonmetal",
  "number": 8,
  "period": 2,
  "group": 16,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Oxygen",
  "summary": "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table and is a highly reactive nonmetal and oxidizing agent that readily forms compounds (notably oxides) with most elements. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium.",
  "symbol": "O",
  "xpos": 16,
  "ypos": 2,
  "wxpos": 30,
  "wypos": 2,
  "shells": [2, 6]
 },
 {
  "name": "Fluorine",
  "appearance": null,
  "atomic_mass": 18.9984031636,
  "boil": 85.03,
  "category": "nonmetal",
  "number": 9,
  "period": 2,
  "group": 17,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Fluorine",
  "summary": "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. As the most electronegative element, it is extremely reactive:almost all other elements, including some noble gases, form compounds with fluorine.",
  "symbol": "F",
  "xpos": 17,
  "ypos": 2,
  "wxpos": 31,
  "wypos": 2,
  "shells": [2, 7]
 },
 {
  "name": "Neon",
  "appearance": "colorless gas exhibiting an orange-red glow when placed in a high voltage electric field",
  "atomic_mass": 20.17976,
  "boil": 27.104,
  "category": "noble gas",
  "number": 10,
  "period": 2,
  "group": 18,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Neon",
  "summary": "Neon is a chemical element with symbol Ne and atomic number 10. It is in group 18 (noble gases) of the periodic table. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
  "symbol": "Ne",
  "xpos": 18,
  "ypos": 2,
  "wxpos": 32,
  "wypos": 2,
  "shells": [2, 8]
 },
 {
  "name": "Sodium",
  "appearance": "silvery white metallic",
  "atomic_mass": 22.989769282,
  "boil": 1156.09,
  "category": "alkali metal",
  "number": 11,
  "period": 3,
  "group": 1,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Sodium",
  "summary": "Sodium is a chemical element with symbol Na (from Ancient Greek Νάτριο) and atomic number 11. It is a soft, silver-white, highly reactive metal. In the Periodic table it is in column 1 (alkali metals), and shares with the other six elements in that column that it has a single electron in its outer shell, which it readily donates, creating a positively charged atom - a cation.",
  "symbol": "Na",
  "xpos": 1,
  "ypos": 3,
  "wxpos": 1,
  "wypos": 3,
  "shells": [2, 8, 1]
 },
 {
  "name": "Magnesium",
  "appearance": "shiny grey solid",
  "atomic_mass": 24.305,
  "boil": 1363,
  "category": "alkaline earth metal",
  "number": 12,
  "period": 3,
  "group": 2,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Magnesium",
  "summary": "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (Group 2, or alkaline earth metals) of the periodic table:they each have the same electron configuration in their outer electron shell producing a similar crystal structure. Magnesium is the ninth most abundant element in the universe.",
  "symbol": "Mg",
  "xpos": 2,
  "ypos": 3,
  "wxpos": 2,
  "wypos": 3,
  "shells": [2, 8, 2]
 },
 {
  "name": "Aluminium",
  "appearance": "silvery gray metallic",
  "atomic_mass": 26.98153857,
  "boil": 2743,
  "category": "post-transition metal",
  "number": 13,
  "period": 3,
  "group": 13,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Aluminium",
  "summary": "Aluminium (or aluminum; see different endings) is a chemical element in the boron group with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal. Aluminium is the third most abundant element (after oxygen and silicon), and the most abundant metal, in the Earth's crust.",
  "symbol": "Al",
  "xpos": 13,
  "ypos": 3,
  "wxpos": 27,
  "wypos": 3,
  "shells": [2, 8, 3]
 },
 {
  "name": "Silicon",
  "appearance": "crystalline, reflective with bluish-tinged faces",
  "atomic_mass": 28.085,
  "boil": 3538,
  "category": "metalloid",
  "number": 14,
  "period": 3,
  "group": 14,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Silicon",
  "summary": "Silicon is a chemical element with symbol Si and atomic number 14. It is a tetravalent metalloid, more reactive than germanium, the metalloid directly below it in the table. Controversy about silicon's character dates to its discovery.",
  "symbol": "Si",
  "xpos": 14,
  "ypos": 3,
  "wxpos": 28,
  "wypos": 3,
  "shells": [2, 8, 4]
 },
 {
  "name": "Phosphorus",
  "appearance": "colourless, waxy white, yellow, scarlet, red, violet, black",
  "atomic_mass": 30.9737619985,
  "boil": null,
  "category": "nonmetal",
  "number": 15,
  "period": 3,
  "group": 15,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Phosphorus",
  "summary": "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus—but due to its high reactivity, phosphorus is never found as a free element on Earth. Instead phosphorus-containing minerals are almost always present in their maximally oxidised state, as inorganic phosphate rocks.",
  "symbol": "P",
  "xpos": 15,
  "ypos": 3,
  "wxpos": 29,
  "wypos": 3,
  "shells": [2, 8, 5]
 },
 {
  "name": "Sulfur",
  "appearance": "lemon yellow sintered microcrystals",
  "atomic_mass": 32.06,
  "boil": 717.8,
  "category": "nonmetal",
  "number": 16,
  "period": 3,
  "group": 16,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Sulfur",
  "summary": "Sulfur or sulphur (see spelling differences) is a chemical element with symbol S and atomic number 16. It is an abundant, multivalent non-metal. Under normal conditions, sulfur atoms form cyclic octatomic molecules with chemical formula S8.",
  "symbol": "S",
  "xpos": 16,
  "ypos": 3,
  "wxpos": 30,
  "wypos": 3,
  "shells": [2, 8, 6]
 },
 {
  "name": "Chlorine",
  "appearance": "pale yellow-green gas",
  "atomic_mass": 35.45,
  "boil": 239.11,
  "category": "nonmetal",
  "number": 17,
  "period": 3,
  "group": 17,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Chlorine",
  "summary": "Chlorine is a chemical element with symbol Cl and atomic number 17. It also has a relative atomic mass of 35.5. Chlorine is in the halogen group (17) and is the second lightest halogen following fluorine.",
  "symbol": "Cl",
  "xpos": 17,
  "ypos": 3,
  "wxpos": 31,
  "wypos": 3,
  "shells": [2, 8, 7]
 },
 {
  "name": "Argon",
  "appearance": "colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field",
  "atomic_mass": 39.9481,
  "boil": 87.302,
  "category": "noble gas",
  "number": 18,
  "period": 3,
  "group": 18,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Argon",
  "summary": "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most common gas in the Earth's atmosphere, at 0.934% (9,340 ppmv), making it over twice as abundant as the next most common atmospheric gas, water vapor (which averages about 4000 ppmv, but varies greatly), and 23 times as abundant as the next most common non-condensing atmospheric gas, carbon dioxide (400 ppmv), and more than 500 times as abundant as the next most common noble gas, neon (18 ppmv).",
  "symbol": "Ar",
  "xpos": 18,
  "ypos": 3,
  "wxpos": 32,
  "wypos": 3,
  "shells": [2, 8, 8]
 },
 {
  "name": "Potassium",
  "appearance": "silvery gray",
  "atomic_mass": 39.09831,
  "boil": 1032,
  "category": "alkali metal",
  "number": 19,
  "period": 4,
  "group": 1,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Potassium",
  "summary": "Potassium is a chemical element with symbol K (derived from Neo-Latin, kalium) and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name is derived. In the Periodic table, potassium is one of seven elements in column (group) 1 (alkali metals):they all have a single valence electron in their outer electron shell, which they readily give up to create an atom with a positive charge - a cation, and combine with anions to form salts.",
  "symbol": "K",
  "xpos": 1,
  "ypos": 4,
  "wxpos": 1,
  "wypos": 4,
  "shells": [2, 8, 8, 1]
 },
 {
  "name": "Calcium",
  "appearance": null,
  "atomic_mass": 40.0784,
  "boil": 1757,
  "category": "alkaline earth metal",
  "number": 20,
  "period": 4,
  "group": 2,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Calcium",
  "summary": "Calcium is a chemical element with symbol Ca and atomic number 20. Calcium is a soft gray alkaline earth metal, fifth-most-abundant element by mass in the Earth's crust. The ion Ca2+ is also the fifth-most-abundant dissolved ion in seawater by both molarity and mass, after sodium, chloride, magnesium, and sulfate.",
  "symbol": "Ca",
  "xpos": 2,
  "ypos": 4,
  "wxpos": 2,
  "wypos": 4,
  "shells": [2, 8, 8, 2]
 },
 {
  "name": "Scandium",
  "appearance": "silvery white",
  "atomic_mass": 44.9559085,
  "boil": 3109,
  "category": "transition metal",
  "number": 21,
  "period": 4,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Scandium",
  "summary": "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been sometimes classified as a rare earth element, together with yttrium and the lanthanoids. It was discovered in 1879 by spectral analysis of the minerals euxenite and gadolinite from Scandinavia.",
  "symbol": "Sc",
  "xpos": 3,
  "ypos": 4,
  "wxpos": 17,
  "wypos": 4,
  "shells": [2, 8, 9, 2]
 },
 {
  "name": "Titanium",
  "appearance": "silvery grey-white metallic",
  "atomic_mass": 47.8671,
  "boil": 3560,
  "category": "transition metal",
  "number": 22,
  "period": 4,
  "group": 4,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Titanium",
  "summary": "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density and high strength. It is highly resistant to corrosion in sea water, aqua regia and chlorine.",
  "symbol": "Ti",
  "xpos": 4,
  "ypos": 4,
  "wxpos": 18,
  "wypos": 4,
  "shells": [2, 8, 10, 2]
 },
 {
  "name": "Vanadium",
  "appearance": "blue-silver-grey metal",
  "atomic_mass": 50.94151,
  "boil": 3680,
  "category": "transition metal",
  "number": 23,
  "period": 4,
  "group": 5,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Vanadium",
  "summary": "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery grey, ductile and malleable transition metal. The element is found only in chemically combined form in nature, but once isolated artificially, the formation of an oxide layer stabilizes the free metal somewhat against further oxidation.",
  "symbol": "V",
  "xpos": 5,
  "ypos": 4,
  "wxpos": 19,
  "wypos": 4,
  "shells": [2, 8, 11, 2]
 },
 {
  "name": "Chromium",
  "appearance": "silvery metallic",
  "atomic_mass": 51.99616,
  "boil": 2944,
  "category": "transition metal",
  "number": 24,
  "period": 4,
  "group": 6,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Chromium",
  "summary": "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in Group 6. It is a steely-gray, lustrous, hard and brittle metal which takes a high polish, resists tarnishing, and has a high melting point.",
  "symbol": "Cr",
  "xpos": 6,
  "ypos": 4,
  "wxpos": 20,
  "wypos": 4,
  "shells": [2, 8, 13, 1]
 },
 {
  "name": "Manganese",
  "appearance": "silvery metallic",
  "atomic_mass": 54.9380443,
  "boil": 2334,
  "category": "transition metal",
  "number": 25,
  "period": 4,
  "group": 7,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Manganese",
  "summary": "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in combination with iron, and in many minerals. Manganese is a metal with important industrial metal alloy uses, particularly in stainless steels.",
  "symbol": "Mn",
  "xpos": 7,
  "ypos": 4,
  "wxpos": 21,
  "wypos": 4,
  "shells": [2, 8, 13, 2]
 },
 {
  "name": "Iron",
  "appearance": "lustrous metallic with a grayish tinge",
  "atomic_mass": 55.8452,
  "boil": 3134,
  "category": "transition metal",
  "number": 26,
  "period": 4,
  "group": 8,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Iron",
  "summary": "Iron is a chemical element with symbol Fe (from Latin:ferrum) and atomic number 26. It is a metal in the first transition series. It is by mass the most common element on Earth, forming much of Earth's outer and inner core.",
  "symbol": "Fe",
  "xpos": 8,
  "ypos": 4,
  "wxpos": 22,
  "wypos": 4,
  "shells": [2, 8, 14, 2]
 },
 {
  "name": "Cobalt",
  "appearance": "hard lustrous gray metal",
  "atomic_mass": 58.9331944,
  "boil": 3200,
  "category": "transition metal",
  "number": 27,
  "period": 4,
  "group": 9,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Cobalt",
  "summary": "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt in the Earth's crust is found only in chemically combined form, save for small deposits found in alloys of natural meteoric iron. The free element, produced by reductive smelting, is a hard, lustrous, silver-gray metal.",
  "symbol": "Co",
  "xpos": 9,
  "ypos": 4,
  "wxpos": 23,
  "wypos": 4,
  "shells": [2, 8, 15, 2]
 },
 {
  "name": "Nickel",
  "appearance": "lustrous, metallic, and silver with a gold tinge",
  "atomic_mass": 58.69344,
  "boil": 3003,
  "category": "transition metal",
  "number": 28,
  "period": 4,
  "group": 10,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Nickel",
  "summary": "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge. Nickel belongs to the transition metals and is hard and ductile.",
  "symbol": "Ni",
  "xpos": 10,
  "ypos": 4,
  "wxpos": 24,
  "wypos": 4,
  "shells": [2, 8, 16, 2]
 },
 {
  "name": "Copper",
  "appearance": "red-orange metallic luster",
  "atomic_mass": 63.5463,
  "boil": 2835,
  "category": "transition metal",
  "number": 29,
  "period": 4,
  "group": 11,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Copper",
  "summary": "Copper is a chemical element with symbol Cu (from Latin:cuprum) and atomic number 29. It is a soft, malleable and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a reddish-orange color.",
  "symbol": "Cu",
  "xpos": 11,
  "ypos": 4,
  "wxpos": 25,
  "wypos": 4,
  "shells": [2, 8, 18, 1]
 },
 {
  "name": "Zinc",
  "appearance": "silver-gray",
  "atomic_mass": 65.382,
  "boil": 1180,
  "category": "transition metal",
  "number": 30,
  "period": 4,
  "group": 12,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Zinc",
  "summary": "Zinc, in commerce also spelter, is a chemical element with symbol Zn and atomic number 30. It is the first element of group 12 of the periodic table. In some respects zinc is chemically similar to magnesium:its ion is of similar size and its only common oxidation state is +2.",
  "symbol": "Zn",
  "xpos": 12,
  "ypos": 4,
  "wxpos": 26,
  "wypos": 4,
  "shells": [2, 8, 18, 2]
 },
 {
  "name": "Gallium",
  "appearance": "silver-white",
  "atomic_mass": 69.7231,
  "boil": 2673,
  "category": "post-transition metal",
  "number": 31,
  "period": 4,
  "group": 13,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Gallium",
  "summary": "Gallium is a chemical element with symbol Ga and atomic number 31. Elemental gallium does not occur in free form in nature, but as the gallium(III) compounds that are in trace amounts in zinc ores and in bauxite. Gallium is a soft, silvery metal, and elemental gallium is a brittle solid at low temperatures, and melts at 29.76 °C (85.57 °F) (slightly above room temperature).",
  "symbol": "Ga",
  "xpos": 13,
  "ypos": 4,
  "wxpos": 27,
  "wypos": 4,
  "shells": [2, 8, 18, 3]
 },
 {
  "name": "Germanium",
  "appearance": "grayish-white",
  "atomic_mass": 72.6308,
  "boil": 3106,
  "category": "metalloid",
  "number": 32,
  "period": 4,
  "group": 14,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Germanium",
  "summary": "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group, chemically similar to its group neighbors tin and silicon. Purified germanium is a semiconductor, with an appearance most similar to elemental silicon.",
  "symbol": "Ge",
  "xpos": 14,
  "ypos": 4,
  "wxpos": 28,
  "wypos": 4,
  "shells": [2, 8, 18, 4]
 },
 {
  "name": "Arsenic",
  "appearance": "metallic grey",
  "atomic_mass": 74.9215956,
  "boil": null,
  "category": "metalloid",
  "number": 33,
  "period": 4,
  "group": 15,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Arsenic",
  "summary": "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in conjunction with sulfur and metals, and also as a pure elemental crystal. Arsenic is a metalloid.",
  "symbol": "As",
  "xpos": 15,
  "ypos": 4,
  "wxpos": 29,
  "wypos": 4,
  "shells": [2, 8, 18, 5]
 },
 {
  "name": "Selenium",
  "appearance": "black, red, and gray (not pictured) allotropes",
  "atomic_mass": 78.9718,
  "boil": 958,
  "category": "nonmetal",
  "number": 34,
  "period": 4,
  "group": 16,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Selenium",
  "summary": "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between those of its periodic table column-adjacent chalcogen elements sulfur and tellurium. It rarely occurs in its elemental state in nature, or as pure ore compounds.",
  "symbol": "Se",
  "xpos": 16,
  "ypos": 4,
  "wxpos": 30,
  "wypos": 4,
  "shells": [2, 8, 18, 6]
 },
 {
  "name": "Bromine",
  "appearance": null,
  "atomic_mass": 79.904,
  "boil": 332,
  "category": "nonmetal",
  "number": 35,
  "period": 4,
  "group": 17,
  "phase": "Liquid",
  "source": "https://en.wikipedia.org/wiki/Bromine",
  "summary": "Bromine is a chemical element with symbol Br, and atomic number 35. It is a halogen. The element was isolated independently by two chemists, Carl Jacob Löwig and Antoine Jerome Balard, in 1825–1826.",
  "symbol": "Br",
  "xpos": 17,
  "ypos": 4,
  "wxpos": 31,
  "wypos": 4,
  "shells": [2, 8, 18, 7]
 },
 {
  "name": "Krypton",
  "appearance": "colorless gas, exhibiting a whitish glow in a high electric field",
  "atomic_mass": 83.7982,
  "boil": 119.93,
  "category": "noble gas",
  "number": 36,
  "period": 4,
  "group": 18,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Krypton",
  "summary": "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere, is isolated by fractionally distilling liquefied air, and is often used with other rare gases in fluorescent lamps.",
  "symbol": "Kr",
  "xpos": 18,
  "ypos": 4,
  "wxpos": 32,
  "wypos": 4,
  "shells": [2, 8, 18, 8]
 },
 {
  "name": "Rubidium",
  "appearance": "grey white",
  "atomic_mass": 85.46783,
  "boil": 961,
  "category": "alkali metal",
  "number": 37,
  "period": 5,
  "group": 1,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Rubidium",
  "summary": "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group, with an atomic mass of 85.4678. Elemental rubidium is highly reactive, with properties similar to those of other alkali metals, such as very rapid oxidation in air.",
  "symbol": "Rb",
  "xpos": 1,
  "ypos": 5,
  "wxpos": 1,
  "wypos": 5,
  "shells": [2, 8, 18, 8, 1]
 },
 {
  "name": "Strontium",
  "appearance": null,
  "atomic_mass": 87.621,
  "boil": 1650,
  "category": "alkaline earth metal",
  "number": 38,
  "period": 5,
  "group": 2,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Strontium",
  "summary": "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white or yellowish metallic element that is highly reactive chemically. The metal turns yellow when it is exposed to air.",
  "symbol": "Sr",
  "xpos": 2,
  "ypos": 5,
  "wxpos": 2,
  "wypos": 5,
  "shells": [2, 8, 18, 8, 2]
 },
 {
  "name": "Yttrium",
  "appearance": "silvery white",
  "atomic_mass": 88.905842,
  "boil": 3203,
  "category": "transition metal",
  "number": 39,
  "period": 5,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Yttrium",
  "summary": "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and it has often been classified as a \\\"rare earth element\\\". Yttrium is almost always found combined with the lanthanides in rare earth minerals and is never found in nature as a free element.",
  "symbol": "Y",
  "xpos": 3,
  "ypos": 5,
  "wxpos": 17,
  "wypos": 5,
  "shells": [2, 8, 18, 9, 2]
 },
 {
  "name": "Zirconium",
  "appearance": "silvery white",
  "atomic_mass": 91.2242,
  "boil": 4650,
  "category": "transition metal",
  "number": 40,
  "period": 5,
  "group": 4,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Zirconium",
  "summary": "Zirconium is a chemical element with symbol Zr and atomic number 40. The name of zirconium is taken from the name of the mineral zircon, the most important source of zirconium. The word zircon comes from the Persian word zargun زرگون, meaning \\\"gold-colored\\\".",
  "symbol": "Zr",
  "xpos": 4,
  "ypos": 5,
  "wxpos": 18,
  "wypos": 5,
  "shells": [2, 8, 18, 10, 2]
 },
 {
  "name": "Niobium",
  "appearance": "gray metallic, bluish when oxidized",
  "atomic_mass": 92.906372,
  "boil": 5017,
  "category": "transition metal",
  "number": 41,
  "period": 5,
  "group": 5,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Niobium",
  "summary": "Niobium, formerly columbium, is a chemical element with symbol Nb (formerly Cb) and atomic number 41. It is a soft, grey, ductile transition metal, which is often found in the pyrochlore mineral, the main commercial source for niobium, and columbite. The name comes from Greek mythology:Niobe, daughter of Tantalus since it is so similar to tantalum.",
  "symbol": "Nb",
  "xpos": 5,
  "ypos": 5,
  "wxpos": 19,
  "wypos": 5,
  "shells": [2, 8, 18, 12, 1]
 },
 {
  "name": "Molybdenum",
  "appearance": "gray metallic",
  "atomic_mass": 95.951,
  "boil": 4912,
  "category": "transition metal",
  "number": 42,
  "period": 5,
  "group": 6,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Molybdenum",
  "summary": "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores. Molybdenum minerals have been known throughout history, but the element was discovered (in the sense of differentiating it as a new entity from the mineral salts of other metals) in 1778 by Carl Wilhelm Scheele.",
  "symbol": "Mo",
  "xpos": 6,
  "ypos": 5,
  "wxpos": 20,
  "wypos": 5,
  "shells": [2, 8, 18, 13, 1]
 },
 {
  "name": "Technetium",
  "appearance": "shiny gray metal",
  "atomic_mass": 98,
  "boil": 4538,
  "category": "transition metal",
  "number": 43,
  "period": 5,
  "group": 7,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Technetium",
  "summary": "Technetium (/tɛkˈniːʃiəm/) is a chemical element with symbol Tc and atomic number 43. It is the element with the lowest atomic number in the periodic table that has no stable isotopes:every form of it is radioactive. Nearly all technetium is produced synthetically, and only minute amounts are found in nature.",
  "symbol": "Tc",
  "xpos": 7,
  "ypos": 5,
  "wxpos": 21,
  "wypos": 5,
  "shells": [2, 8, 18, 13, 2]
 },
 {
  "name": "Ruthenium",
  "appearance": "silvery white metallic",
  "atomic_mass": 101.072,
  "boil": 4423,
  "category": "transition metal",
  "number": 44,
  "period": 5,
  "group": 8,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Ruthenium",
  "summary": "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table. Like the other metals of the platinum group, ruthenium is inert to most other chemicals.",
  "symbol": "Ru",
  "xpos": 8,
  "ypos": 5,
  "wxpos": 22,
  "wypos": 5,
  "shells": [2, 8, 18, 15, 1]
 },
 {
  "name": "Rhodium",
  "appearance": "silvery white metallic",
  "atomic_mass": 102.905502,
  "boil": 3968,
  "category": "transition metal",
  "number": 45,
  "period": 5,
  "group": 9,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Rhodium",
  "summary": "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, and chemically inert transition metal. It is a member of the platinum group.",
  "symbol": "Rh",
  "xpos": 9,
  "ypos": 5,
  "wxpos": 23,
  "wypos": 5,
  "shells": [2, 8, 18, 16, 1]
 },
 {
  "name": "Palladium",
  "appearance": "silvery white",
  "atomic_mass": 106.421,
  "boil": 3236,
  "category": "transition metal",
  "number": 46,
  "period": 5,
  "group": 10,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Palladium",
  "summary": "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston. He named it after the asteroid Pallas, which was itself named after the epithet of the Greek goddess Athena, acquired by her when she slew Pallas.",
  "symbol": "Pd",
  "xpos": 10,
  "ypos": 5,
  "wxpos": 24,
  "wypos": 5,
  "shells": [2, 8, 18, 18]
 },
 {
  "name": "Silver",
  "appearance": "lustrous white metal",
  "atomic_mass": 107.86822,
  "boil": 2435,
  "category": "transition metal",
  "number": 47,
  "period": 5,
  "group": 11,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Silver",
  "summary": "Silver is a chemical element with symbol Ag (Greek:άργυρος árguros, Latin:argentum, both from the Indo-European root *h₂erǵ- for \\\"grey\\\" or \\\"shining\\\") and atomic number 47. A soft, white, lustrous transition metal, it possesses the highest electrical conductivity, thermal conductivity and reflectivity of any metal. The metal occurs naturally in its pure, free form (native silver), as an alloy with gold and other metals, and in minerals such as argentite and chlorargyrite.",
  "symbol": "Ag",
  "xpos": 11,
  "ypos": 5,
  "wxpos": 25,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 1]
 },
 {
  "name": "Cadmium",
  "appearance": "silvery bluish-gray metallic",
  "atomic_mass": 112.4144,
  "boil": 1040,
  "category": "transition metal",
  "number": 48,
  "period": 5,
  "group": 12,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Cadmium",
  "summary": "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury. Like zinc, it prefers oxidation state +2 in most of its compounds and like mercury it shows a low melting point compared to transition metals.",
  "symbol": "Cd",
  "xpos": 12,
  "ypos": 5,
  "wxpos": 26,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 2]
 },
 {
  "name": "Indium",
  "appearance": "silvery lustrous gray",
  "atomic_mass": 114.8181,
  "boil": 2345,
  "category": "post-transition metal",
  "number": 49,
  "period": 5,
  "group": 13,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Indium",
  "summary": "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metallic element that is rare in Earth's crust. The metal is very soft, malleable and easily fusible, with a melting point higher than sodium, but lower than lithium or tin.",
  "symbol": "In",
  "xpos": 13,
  "ypos": 5,
  "wxpos": 27,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 3]
 },
 {
  "name": "Tin",
  "appearance": "silvery-white (beta, β) or gray (alpha, α)",
  "atomic_mass": 118.7107,
  "boil": 2875,
  "category": "post-transition metal",
  "number": 50,
  "period": 5,
  "group": 14,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Tin",
  "summary": "Tin is a chemical element with the symbol Sn (for Latin:stannum) and atomic number 50. It is a main group metal in group 14 of the periodic table. Tin shows a chemical similarity to both neighboring group-14 elements, germanium and lead, and has two possible oxidation states, +2 and the slightly more stable +4.",
  "symbol": "Sn",
  "xpos": 14,
  "ypos": 5,
  "wxpos": 28,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 4]
 },
 {
  "name": "Antimony",
  "appearance": "silvery lustrous gray",
  "atomic_mass": 121.7601,
  "boil": 1908,
  "category": "metalloid",
  "number": 51,
  "period": 5,
  "group": 15,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Antimony",
  "summary": "Antimony is a chemical element with symbol Sb (from Latin:stibium) and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3). Antimony compounds have been known since ancient times and were used for cosmetics; metallic antimony was also known, but it was erroneously identified as lead upon its discovery.",
  "symbol": "Sb",
  "xpos": 15,
  "ypos": 5,
  "wxpos": 29,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 5]
 },
 {
  "name": "Tellurium",
  "appearance": null,
  "atomic_mass": 127.603,
  "boil": 1261,
  "category": "metalloid",
  "number": 52,
  "period": 5,
  "group": 16,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Tellurium",
  "summary": "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur.",
  "symbol": "Te",
  "xpos": 16,
  "ypos": 5,
  "wxpos": 30,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 6]
 },
 {
  "name": "Iodine",
  "appearance": "lustrous metallic gray, violet as a gas",
  "atomic_mass": 126.904473,
  "boil": 457.4,
  "category": "nonmetal",
  "number": 53,
  "period": 5,
  "group": 17,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Iodine",
  "summary": "Iodine is a chemical element with symbol I and atomic number 53. The name is from Greek ἰοειδής ioeidēs, meaning violet or purple, due to the color of iodine vapor. Iodine and its compounds are primarily used in nutrition, and industrially in the production of acetic acid and certain polymers.",
  "symbol": "I",
  "xpos": 17,
  "ypos": 5,
  "wxpos": 31,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 7]
 },
 {
  "name": "Xenon",
  "appearance": "colorless gas, exhibiting a blue glow when placed in a high voltage electric field",
  "atomic_mass": 131.2936,
  "boil": 165.051,
  "category": "noble gas",
  "number": 54,
  "period": 5,
  "group": 18,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Xenon",
  "summary": "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas, that occurs in the Earth's atmosphere in trace amounts. Although generally unreactive, xenon can undergo a few chemical reactions such as the formation of xenon hexafluoroplatinate, the first noble gas compound to be synthesized.",
  "symbol": "Xe",
  "xpos": 18,
  "ypos": 5,
  "wxpos": 32,
  "wypos": 5,
  "shells": [2, 8, 18, 18, 8]
 },
 {
  "name": "Cesium",
  "appearance": "silvery gold",
  "atomic_mass": 132.905451966,
  "boil": 944,
  "category": "alkali metal",
  "number": 55,
  "period": 6,
  "group": 1,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Cesium",
  "summary": "Caesium or cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28 °C (82 °F), which makes it one of only five elemental metals that are liquid at or near room temperature. Caesium is an alkali metal and has physical and chemical properties similar to those of rubidium and potassium.",
  "symbol": "Cs",
  "xpos": 1,
  "ypos": 6,
  "wxpos": 1,
  "wypos": 6,
  "shells": [2, 8, 18, 18, 8, 1]
 },
 {
  "name": "Barium",
  "appearance": null,
  "atomic_mass": 137.3277,
  "boil": 2118,
  "category": "alkaline earth metal",
  "number": 56,
  "period": 6,
  "group": 2,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Barium",
  "summary": "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in Group 2, a soft silvery metallic alkaline earth metal. Because of its high chemical reactivity barium is never found in nature as a free element.",
  "symbol": "Ba",
  "xpos": 2,
  "ypos": 6,
  "wxpos": 2,
  "wypos": 6,
  "shells": [2, 8, 18, 18, 8, 2]
 },
 {
  "name": "Lanthanum",
  "appearance": "silvery white",
  "atomic_mass": 138.905477,
  "boil": 3737,
  "category": "lanthanide",
  "number": 57,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Lanthanum",
  "summary": "Lanthanum is a soft, ductile, silvery-white metallic chemical element with symbol La and atomic number 57. It tarnishes rapidly when exposed to air and is soft enough to be cut with a knife. It gave its name to the lanthanide series, a group of 15 similar elements between lanthanum and lutetium in the periodic table:it is also sometimes considered the first element of the 6th-period transition metals.",
  "symbol": "La",
  "xpos": 3,
  "ypos": 9,
  "wxpos": 3,
  "wypos": 6,
  "shells": [2, 8, 18, 18, 9, 2]
 },
 {
  "name": "Cerium",
  "appearance": "silvery white",
  "atomic_mass": 140.1161,
  "boil": 3716,
  "category": "lanthanide",
  "number": 58,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Cerium",
  "summary": "Cerium is a chemical element with symbol Ce and atomic number 58. It is a soft, silvery, ductile metal which easily oxidizes in air. Cerium was named after the dwarf planet Ceres (itself named after the Roman goddess of agriculture).",
  "symbol": "Ce",
  "xpos": 4,
  "ypos": 9,
  "wxpos": 4,
  "wypos": 6,
  "shells": [2, 8, 18, 19, 9, 2]
 },
 {
  "name": "Praseodymium",
  "appearance": "grayish white",
  "atomic_mass": 140.907662,
  "boil": 3403,
  "category": "lanthanide",
  "number": 59,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Praseodymium",
  "summary": "Praseodymium is a chemical element with symbol Pr and atomic number 59. Praseodymium is a soft, silvery, malleable and ductile metal in the lanthanide group. It is valued for its magnetic, electrical, chemical, and optical properties.",
  "symbol": "Pr",
  "xpos": 5,
  "ypos": 9,
  "wxpos": 5,
  "wypos": 6,
  "shells": [2, 8, 18, 21, 8, 2]
 },
 {
  "name": "Neodymium",
  "appearance": "silvery white",
  "atomic_mass": 144.2423,
  "boil": 3347,
  "category": "lanthanide",
  "number": 60,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Neodymium",
  "summary": "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach.",
  "symbol": "Nd",
  "xpos": 6,
  "ypos": 9,
  "wxpos": 6,
  "wypos": 6,
  "shells": [2, 8, 18, 22, 8, 2]
 },
 {
  "name": "Promethium",
  "appearance": "metallic",
  "atomic_mass": 145,
  "boil": 3273,
  "category": "lanthanide",
  "number": 61,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Promethium",
  "summary": "Promethium, originally prometheum, is a chemical element with the symbol Pm and atomic number 61. All of its isotopes are radioactive; it is one of only two such elements that are followed in the periodic table by elements with stable forms, a distinction shared with technetium. Chemically, promethium is a lanthanide, which forms salts when combined with other elements.",
  "symbol": "Pm",
  "xpos": 7,
  "ypos": 9,
  "wxpos": 7,
  "wypos": 6,
  "shells": [2, 8, 18, 23, 8, 2]
 },
 {
  "name": "Samarium",
  "appearance": "silvery white",
  "atomic_mass": 150.362,
  "boil": 2173,
  "category": "lanthanide",
  "number": 62,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Samarium",
  "summary": "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that readily oxidizes in air. Being a typical member of the lanthanide series, samarium usually assumes the oxidation state +3.",
  "symbol": "Sm",
  "xpos": 8,
  "ypos": 9,
  "wxpos": 8,
  "wypos": 6,
  "shells": [2, 8, 18, 24, 8, 2]
 },
 {
  "name": "Europium",
  "appearance": null,
  "atomic_mass": 151.9641,
  "boil": 1802,
  "category": "lanthanide",
  "number": 63,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Europium",
  "summary": "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe. It is a moderately hard, silvery metal which readily oxidizes in air and water.",
  "symbol": "Eu",
  "xpos": 9,
  "ypos": 9,
  "wxpos": 9,
  "wypos": 6,
  "shells": [2, 8, 18, 25, 8, 2]
 },
 {
  "name": "Gadolinium",
  "appearance": "silvery white",
  "atomic_mass": 157.253,
  "boil": 3273,
  "category": "lanthanide",
  "number": 64,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Gadolinium",
  "summary": "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white, malleable and ductile rare-earth metal. It is found in nature only in combined (salt) form.",
  "symbol": "Gd",
  "xpos": 10,
  "ypos": 9,
  "wxpos": 10,
  "wypos": 6,
  "shells": [2, 8, 18, 25, 9, 2]
 },
 {
  "name": "Terbium",
  "appearance": "silvery white",
  "atomic_mass": 158.925352,
  "boil": 3396,
  "category": "lanthanide",
  "number": 65,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Terbium",
  "summary": "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white rare earth metal that is malleable, ductile and soft enough to be cut with a knife. Terbium is never found in nature as a free element, but it is contained in many minerals, including cerite, gadolinite, monazite, xenotime and euxenite.",
  "symbol": "Tb",
  "xpos": 11,
  "ypos": 9,
  "wxpos": 11,
  "wypos": 6,
  "shells": [2, 8, 18, 27, 8, 2]
 },
 {
  "name": "Dysprosium",
  "appearance": "silvery white",
  "atomic_mass": 162.5001,
  "boil": 2840,
  "category": "lanthanide",
  "number": 66,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Dysprosium",
  "summary": "Dysprosium is a chemical element with the symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in various minerals, such as xenotime.",
  "symbol": "Dy",
  "xpos": 12,
  "ypos": 9,
  "wxpos": 12,
  "wypos": 6,
  "shells": [2, 8, 18, 28, 8, 2]
 },
 {
  "name": "Holmium",
  "appearance": "silvery white",
  "atomic_mass": 164.930332,
  "boil": 2873,
  "category": "lanthanide",
  "number": 67,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Holmium",
  "summary": "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare earth element. Holmium was discovered by Swedish chemist Per Theodor Cleve.",
  "symbol": "Ho",
  "xpos": 13,
  "ypos": 9,
  "wxpos": 13,
  "wypos": 6,
  "shells": [2, 8, 18, 29, 8, 2]
 },
 {
  "name": "Erbium",
  "appearance": "silvery white",
  "atomic_mass": 167.2593,
  "boil": 3141,
  "category": "lanthanide",
  "number": 68,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Erbium",
  "summary": "Erbium is a chemical element in the lanthanide series, with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements on Earth. As such, it is a rare earth element which is associated with several other rare elements in the mineral gadolinite from Ytterby in Sweden, where yttrium, ytterbium, and terbium were discovered.",
  "symbol": "Er",
  "xpos": 14,
  "ypos": 9,
  "wxpos": 14,
  "wypos": 6,
  "shells": [2, 8, 18, 30, 8, 2]
 },
 {
  "name": "Thulium",
  "appearance": "silvery gray",
  "atomic_mass": 168.934222,
  "boil": 2223,
  "category": "lanthanide",
  "number": 69,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Thulium",
  "summary": "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and antepenultimate (third-last) element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds.",
  "symbol": "Tm",
  "xpos": 15,
  "ypos": 9,
  "wxpos": 15,
  "wypos": 6,
  "shells": [2, 8, 18, 31, 8, 2]
 },
 {
  "name": "Ytterbium",
  "appearance": null,
  "atomic_mass": 173.0451,
  "boil": 1469,
  "category": "lanthanide",
  "number": 70,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Ytterbium",
  "summary": "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state. However, like the other lanthanides, its most common oxidation state is +3, seen in its oxide, halides and other compounds.",
  "symbol": "Yb",
  "xpos": 16,
  "ypos": 9,
  "wxpos": 16,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 8, 2]
 },
 {
  "name": "Lutetium",
  "appearance": "silvery white",
  "atomic_mass": 174.96681,
  "boil": 3675,
  "category": "lanthanide",
  "number": 71,
  "period": 6,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Lutetium",
  "summary": "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry, but not in moist air. It is considered the first element of the 6th-period transition metals and the last element in the lanthanide series, and is traditionally counted among the rare earths.",
  "symbol": "Lu",
  "xpos": 17,
  "ypos": 9,
  "wxpos": 17,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 9, 2]
 },
 {
  "name": "Hafnium",
  "appearance": "steel gray",
  "atomic_mass": 178.492,
  "boil": 4876,
  "category": "transition metal",
  "number": 72,
  "period": 6,
  "group": 4,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Hafnium",
  "summary": "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in zirconium minerals. Its existence was predicted by Dmitri Mendeleev in 1869, though it was not identified until 1923, making it the penultimate stable element to be discovered (rhenium was identified two years later).",
  "symbol": "Hf",
  "xpos": 4,
  "ypos": 6,
  "wxpos": 18,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 10, 2]
 },
 {
  "name": "Tantalum",
  "appearance": "gray blue",
  "atomic_mass": 180.947882,
  "boil": 5731,
  "category": "transition metal",
  "number": 73,
  "period": 6,
  "group": 5,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Tantalum",
  "summary": "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name comes from Tantalus, an antihero from Greek mythology. Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant.",
  "symbol": "Ta",
  "xpos": 5,
  "ypos": 6,
  "wxpos": 19,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 11, 2]
 },
 {
  "name": "Tungsten",
  "appearance": "grayish white, lustrous",
  "atomic_mass": 183.841,
  "boil": 6203,
  "category": "transition metal",
  "number": 74,
  "period": 6,
  "group": 6,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Tungsten",
  "summary": "Tungsten, also known as wolfram, is a chemical element with symbol W and atomic number 74. The word tungsten comes from the Swedish language tung sten, which directly translates to heavy stone. Its name in Swedish is volfram, however, in order to distinguish it from scheelite, which in Swedish is alternatively named tungsten.",
  "symbol": "W",
  "xpos": 6,
  "ypos": 6,
  "wxpos": 20,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 12, 2]
 },
 {
  "name": "Rhenium",
  "appearance": "silvery-grayish",
  "atomic_mass": 186.2071,
  "boil": 5869,
  "category": "transition metal",
  "number": 75,
  "period": 6,
  "group": 7,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Rhenium",
  "summary": "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table. With an estimated average concentration of 1 part per billion (ppb), rhenium is one of the rarest elements in the Earth's crust.",
  "symbol": "Re",
  "xpos": 7,
  "ypos": 6,
  "wxpos": 21,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 13, 2]
 },
 {
  "name": "Osmium",
  "appearance": "silvery, blue cast",
  "atomic_mass": 190.233,
  "boil": 5285,
  "category": "transition metal",
  "number": 76,
  "period": 6,
  "group": 8,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Osmium",
  "summary": "Osmium (from Greek osme (ὀσμή) meaning \\\"smell\\\") is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores. Osmium is the densest naturally occurring element, with a density of 22.59 g/cm3.",
  "symbol": "Os",
  "xpos": 8,
  "ypos": 6,
  "wxpos": 22,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 14, 2]
 },
 {
  "name": "Iridium",
  "appearance": "silvery white",
  "atomic_mass": 192.2173,
  "boil": 4403,
  "category": "transition metal",
  "number": 77,
  "period": 6,
  "group": 9,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Iridium",
  "summary": "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is generally credited with being the second densest element (after osmium) based on measured density, although calculations involving the space lattices of the elements show that iridium is denser. It is also the most corrosion-resistant metal, even at temperatures as high as 2000 °C. Although only certain molten salts and halogens are corrosive to solid iridium, finely divided iridium dust is much more reactive and can be flammable.",
  "symbol": "Ir",
  "xpos": 9,
  "ypos": 6,
  "wxpos": 23,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 15, 2]
 },
 {
  "name": "Platinum",
  "appearance": "silvery white",
  "atomic_mass": 195.0849,
  "boil": 4098,
  "category": "transition metal",
  "number": 78,
  "period": 6,
  "group": 10,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Platinum",
  "summary": "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, gray-white transition metal. Its name is derived from the Spanish term platina, which is literally translated into \\\"little silver\\\".",
  "symbol": "Pt",
  "xpos": 10,
  "ypos": 6,
  "wxpos": 24,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 17, 1]
 },
 {
  "name": "Gold",
  "appearance": "metallic yellow",
  "atomic_mass": 196.9665695,
  "boil": 3243,
  "category": "transition metal",
  "number": 79,
  "period": 6,
  "group": 11,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Gold",
  "summary": "Gold is a chemical element with symbol Au (from Latin:aurum) and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable and ductile metal. Chemically, gold is a transition metal and a group 11 element.",
  "symbol": "Au",
  "xpos": 11,
  "ypos": 6,
  "wxpos": 25,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 1]
 },
 {
  "name": "Mercury",
  "appearance": "silvery",
  "atomic_mass": 200.5923,
  "boil": 629.88,
  "category": "transition metal",
  "number": 80,
  "period": 6,
  "group": 12,
  "phase": "Liquid",
  "source": "https://en.wikipedia.org/wiki/Mercury (Element)",
  "summary": "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum (/haɪˈdrɑːrdʒərəm/). A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure; the only other element that is liquid under these conditions is bromine, though metals such as caesium, gallium, and rubidium melt just above room temperature.",
  "symbol": "Hg",
  "xpos": 12,
  "ypos": 6,
  "wxpos": 26,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 2]
 },
 {
  "name": "Thallium",
  "appearance": "silvery white",
  "atomic_mass": 204.38,
  "boil": 1746,
  "category": "post-transition metal",
  "number": 81,
  "period": 6,
  "group": 13,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Thallium",
  "summary": "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature. When isolated, it resembles tin, but discolors when exposed to air.",
  "symbol": "Tl",
  "xpos": 13,
  "ypos": 6,
  "wxpos": 27,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 3]
 },
 {
  "name": "Lead",
  "appearance": "metallic gray",
  "atomic_mass": 207.21,
  "boil": 2022,
  "category": "post-transition metal",
  "number": 82,
  "period": 6,
  "group": 14,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Lead_(element)",
  "summary": "Lead (/lɛd/) is a chemical element in the carbon group with symbol Pb (from Latin:plumbum) and atomic number 82. Lead is a soft, malleable and heavy post-transition metal. Metallic lead has a bluish-white color after being freshly cut, but it soon tarnishes to a dull grayish color when exposed to air.",
  "symbol": "Pb",
  "xpos": 14,
  "ypos": 6,
  "wxpos": 28,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 4]
 },
 {
  "name": "Bismuth",
  "appearance": "lustrous silver",
  "atomic_mass": 208.980401,
  "boil": 1837,
  "category": "post-transition metal",
  "number": 83,
  "period": 6,
  "group": 15,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Bismuth",
  "summary": "Bismuth is a chemical element with symbol Bi and atomic number 83. Bismuth, a pentavalent post-transition metal, chemically resembles arsenic and antimony. Elemental bismuth may occur naturally, although its sulfide and oxide form important commercial ores.",
  "symbol": "Bi",
  "xpos": 15,
  "ypos": 6,
  "wxpos": 29,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 5]
 },
 {
  "name": "Polonium",
  "appearance": "silvery",
  "atomic_mass": 209,
  "boil": 1235,
  "category": "post-transition metal",
  "number": 84,
  "period": 6,
  "group": 16,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Polonium",
  "summary": "Polonium is a chemical element with symbol Po and atomic number 84, discovered in 1898 by Marie Curie and Pierre Curie. A rare and highly radioactive element with no stable isotopes, polonium is chemically similar to bismuth and tellurium, and it occurs in uranium ores. Applications of polonium are few.",
  "symbol": "Po",
  "xpos": 16,
  "ypos": 6,
  "wxpos": 30,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 6]
 },
 {
  "name": "Astatine",
  "appearance": "metallic",
  "atomic_mass": 210,
  "boil": 610,
  "category": "metalloid",
  "number": 85,
  "period": 6,
  "group": 17,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Astatine",
  "summary": "Astatine is a very rare radioactive chemical element with the chemical symbol At and atomic number 85. It occurs on Earth as the decay product of various heavier elements. All its isotopes are short-lived; the most stable is astatine-210, with a half-life of 8.1 hours.",
  "symbol": "At",
  "xpos": 17,
  "ypos": 6,
  "wxpos": 31,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 7]
 },
 {
  "name": "Radon",
  "appearance": "colorless gas, occasionally glows green or red in discharge tubes",
  "atomic_mass": 222,
  "boil": 211.5,
  "category": "noble gas",
  "number": 86,
  "period": 6,
  "group": 18,
  "phase": "Gas",
  "source": "https://en.wikipedia.org/wiki/Radon",
  "summary": "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas, occurring naturally as a decay product of radium. Its most stable isotope, 222Rn, has a half-life of 3.8 days.",
  "symbol": "Rn",
  "xpos": 18,
  "ypos": 6,
  "wxpos": 32,
  "wypos": 6,
  "shells": [2, 8, 18, 32, 18, 8]
 },
 {
  "name": "Francium",
  "appearance": null,
  "atomic_mass": 223,
  "boil": 950,
  "category": "alkali metal",
  "number": 87,
  "period": 7,
  "group": 1,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Francium",
  "summary": "Francium is a chemical element with symbol Fr and atomic number 87. It used to be known as eka-caesium and actinium K. It is the second-least electronegative element, behind only caesium. Francium is a highly radioactive metal that decays into astatine, radium, and radon.",
  "symbol": "Fr",
  "xpos": 1,
  "ypos": 7,
  "wxpos": 1,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 18, 8, 1]
 },
 {
  "name": "Radium",
  "appearance": "silvery white metallic",
  "atomic_mass": 226,
  "boil": 2010,
  "category": "alkaline earth metal",
  "number": 88,
  "period": 7,
  "group": 2,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Radium",
  "summary": "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals. Pure radium is almost colorless, but it readily combines with nitrogen (rather than oxygen) on exposure to air, forming a black surface layer of radium nitride (Ra3N2).",
  "symbol": "Ra",
  "xpos": 2,
  "ypos": 7,
  "wxpos": 2,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 18, 8, 2]
 },
 {
  "name": "Actinium",
  "appearance": null,
  "atomic_mass": 227,
  "boil": 3500,
  "category": "actinide",
  "number": 89,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Actinium",
  "summary": "Actinium is a radioactive chemical element with symbol Ac (not to be confused with the abbreviation for an acetyl group) and atomic number 89, which was discovered in 1899. It was the first non-primordial radioactive element to be isolated. Polonium, radium and radon were observed before actinium, but they were not isolated until 1902.",
  "symbol": "Ac",
  "xpos": 3,
  "ypos": 10,
  "wxpos": 3,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 18, 9, 2]
 },
 {
  "name": "Thorium",
  "appearance": "silvery, often with black tarnish",
  "atomic_mass": 232.03774,
  "boil": 5061,
  "category": "actinide",
  "number": 90,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Thorium",
  "summary": "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only two significantly radioactive elements that still occur naturally in large quantities as a primordial element (the other being uranium). It was discovered in 1828 by the Norwegian Reverend and amateur mineralogist Morten Thrane Esmark and identified by the Swedish chemist Jöns Jakob Berzelius, who named it after Thor, the Norse god of thunder.",
  "symbol": "Th",
  "xpos": 4,
  "ypos": 10,
  "wxpos": 4,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 18, 10, 2]
 },
 {
  "name": "Protactinium",
  "appearance": "bright, silvery metallic luster",
  "atomic_mass": 231.035882,
  "boil": 4300,
  "category": "actinide",
  "number": 91,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Protactinium",
  "summary": "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray metal which readily reacts with oxygen, water vapor and inorganic acids. It forms various chemical compounds where protactinium is usually present in the oxidation state +5, but can also assume +4 and even +2 or +3 states.",
  "symbol": "Pa",
  "xpos": 5,
  "ypos": 10,
  "wxpos": 5,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 20, 9, 2]
 },
 {
  "name": "Uranium",
  "appearance": null,
  "atomic_mass": 238.028913,
  "boil": 4404,
  "category": "actinide",
  "number": 92,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Uranium",
  "summary": "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-white metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons.",
  "symbol": "U",
  "xpos": 6,
  "ypos": 10,
  "wxpos": 6,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 21, 9, 2]
 },
 {
  "name": "Neptunium",
  "appearance": "silvery metallic",
  "atomic_mass": 237,
  "boil": 4447,
  "category": "actinide",
  "number": 93,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Neptunium",
  "summary": "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium, named after the planet Uranus, led to it being named after Neptune, the next planet beyond Uranus.",
  "symbol": "Np",
  "xpos": 7,
  "ypos": 10,
  "wxpos": 7,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 22, 9, 2]
 },
 {
  "name": "Plutonium",
  "appearance": "silvery white, tarnishing to dark gray in air",
  "atomic_mass": 244,
  "boil": 3505,
  "category": "actinide",
  "number": 94,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Plutonium",
  "summary": "Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized. The element normally exhibits six allotropes and four oxidation states.",
  "symbol": "Pu",
  "xpos": 8,
  "ypos": 10,
  "wxpos": 8,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 24, 8, 2]
 },
 {
  "name": "Americium",
  "appearance": "silvery white",
  "atomic_mass": 243,
  "boil": 2880,
  "category": "actinide",
  "number": 95,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Americium",
  "summary": "Americium is a radioactive transuranic chemical element with symbol Am and atomic number 95. This member of the actinide series is located in the periodic table under the lanthanide element europium, and thus by analogy was named after the Americas. Americium was first produced in 1944 by the group of Glenn T.Seaborg from Berkeley, California, at the metallurgical laboratory of University of Chicago.",
  "symbol": "Am",
  "xpos": 9,
  "ypos": 10,
  "wxpos": 9,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 25, 8, 2]
 },
 {
  "name": "Curium",
  "appearance": "silvery metallic, glows purple in the dark",
  "atomic_mass": 247,
  "boil": 3383,
  "category": "actinide",
  "number": 96,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Curium",
  "summary": "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie – both were known for their research on radioactivity. Curium was first intentionally produced and identified in July 1944 by the group of Glenn T. Seaborg at the University of California, Berkeley.",
  "symbol": "Cm",
  "xpos": 10,
  "ypos": 10,
  "wxpos": 10,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 25, 9, 2]
 },
 {
  "name": "Berkelium",
  "appearance": "silvery",
  "atomic_mass": 247,
  "boil": 2900,
  "category": "actinide",
  "number": 97,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Berkelium",
  "summary": "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series. It is named after the city of Berkeley, California, the location of the University of California Radiation Laboratory where it was discovered in December 1949.",
  "symbol": "Bk",
  "xpos": 11,
  "ypos": 10,
  "wxpos": 11,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 27, 8, 2]
 },
 {
  "name": "Californium",
  "appearance": "silvery",
  "atomic_mass": 251,
  "boil": 1743,
  "category": "actinide",
  "number": 98,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Californium",
  "summary": "Californium is a radioactive metallic chemical element with symbol Cf and atomic number 98. The element was first made in 1950 at the University of California Radiation Laboratory in Berkeley, by bombarding curium with alpha particles (helium-4 ions). It is an actinide element, the sixth transuranium element to be synthesized, and has the second-highest atomic mass of all the elements that have been produced in amounts large enough to see with the unaided eye (after einsteinium).",
  "symbol": "Cf",
  "xpos": 12,
  "ypos": 10,
  "wxpos": 12,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 28, 8, 2]
 },
 {
  "name": "Einsteinium",
  "appearance": "silver-colored",
  "atomic_mass": 252,
  "boil": 1269,
  "category": "actinide",
  "number": 99,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Einsteinium",
  "summary": "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide. Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein.",
  "symbol": "Es",
  "xpos": 13,
  "ypos": 10,
  "wxpos": 13,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 29, 8, 2]
 },
 {
  "name": "Fermium",
  "appearance": null,
  "atomic_mass": 257,
  "boil": null,
  "category": "actinide",
  "number": 100,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Fermium",
  "summary": "Fermium is a synthetic element with symbol Fm and atomic number 100. It is a member of the actinide series. It is the heaviest element that can be formed by neutron bombardment of lighter elements, and hence the last element that can be prepared in macroscopic quantities, although pure fermium metal has not yet been prepared.",
  "symbol": "Fm",
  "xpos": 14,
  "ypos": 10,
  "wxpos": 14,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 30, 8, 2]
 },
 {
  "name": "Mendelevium",
  "appearance": null,
  "atomic_mass": 258,
  "boil": null,
  "category": "actinide",
  "number": 101,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Mendelevium",
  "summary": "Mendelevium is a synthetic element with chemical symbol Md (formerly Mv) and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements. It is the antepenultimate actinide and the ninth transuranic element.",
  "symbol": "Md",
  "xpos": 15,
  "ypos": 10,
  "wxpos": 15,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 31, 8, 2]
 },
 {
  "name": "Nobelium",
  "appearance": null,
  "atomic_mass": 259,
  "boil": null,
  "category": "actinide",
  "number": 102,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Nobelium",
  "summary": "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science. A radioactive metal, it is the tenth transuranic element and is the penultimate member of the actinide series.",
  "symbol": "No",
  "xpos": 16,
  "ypos": 10,
  "wxpos": 16,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 8, 2]
 },
 {
  "name": "Lawrencium",
  "appearance": null,
  "atomic_mass": 266,
  "boil": null,
  "category": "actinide",
  "number": 103,
  "period": 7,
  "group": 3,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Lawrencium",
  "summary": "Lawrencium is a synthetic chemical element with chemical symbol Lr (formerly Lw) and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements. A radioactive metal, lawrencium is the eleventh transuranic element and is also the final member of the actinide series.",
  "symbol": "Lr",
  "xpos": 17,
  "ypos": 10,
  "wxpos": 17,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 8, 3]
 },
 {
  "name": "Rutherfordium",
  "appearance": null,
  "atomic_mass": 267,
  "boil": 5800,
  "category": "transition metal",
  "number": 104,
  "period": 7,
  "group": 4,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Rutherfordium",
  "summary": "Rutherfordium is a chemical element with symbol Rf and atomic number 104, named in honor of physicist Ernest Rutherford. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 267Rf, has a half-life of approximately 1.3 hours. In the periodic table of the elements, it is a d - block element and the second of the fourth - row transition elements.",
  "symbol": "Rf",
  "xpos": 4,
  "ypos": 7,
  "wxpos": 18,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 10, 2]
 },
 {
  "name": "Dubnium",
  "appearance": null,
  "atomic_mass": 268,
  "boil": null,
  "category": "transition metal",
  "number": 105,
  "period": 7,
  "group": 5,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Dubnium",
  "summary": "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia (north of Moscow), where it was first produced. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, dubnium-268, has a half-life of approximately 28 hours.",
  "symbol": "Db",
  "xpos": 5,
  "ypos": 7,
  "wxpos": 19,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 11, 2]
 },
 {
  "name": "Seaborgium",
  "appearance": null,
  "atomic_mass": 269,
  "boil": null,
  "category": "transition metal",
  "number": 106,
  "period": 7,
  "group": 6,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Seaborgium",
  "summary": "Seaborgium is a synthetic element with symbol Sg and atomic number 106. Its most stable isotope 271Sg has a half-life of 1.9 minutes. A more recently discovered isotope 269Sg has a potentially slightly longer half-life (ca.",
  "symbol": "Sg",
  "xpos": 6,
  "ypos": 7,
  "wxpos": 20,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 12, 2]
 },
 {
  "name": "Bohrium",
  "appearance": null,
  "atomic_mass": 270,
  "boil": null,
  "category": "transition metal",
  "number": 107,
  "period": 7,
  "group": 7,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Bohrium",
  "summary": "Bohrium is a chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 270Bh, has a half-life of approximately 61 seconds.",
  "symbol": "Bh",
  "xpos": 7,
  "ypos": 7,
  "wxpos": 21,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 13, 2]
 },
 {
  "name": "Hassium",
  "appearance": null,
  "atomic_mass": 269,
  "boil": null,
  "category": "transition metal",
  "number": 108,
  "period": 7,
  "group": 8,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Hassium",
  "summary": "Hassium is a chemical element with symbol Hs and atomic number 108, named after the German state of Hesse. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 269Hs, has a half-life of approximately 9.7 seconds, although an unconfirmed metastable state, 277mHs, may have a longer half-life of about 130 seconds. More than 100 atoms of hassium have been synthesized to date.",
  "symbol": "Hs",
  "xpos": 8,
  "ypos": 7,
  "wxpos": 22,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 14, 2]
 },
 {
  "name": "Meitnerium",
  "appearance": null,
  "atomic_mass": 278,
  "boil": null,
  "category": "transition metal",
  "number": 109,
  "period": 7,
  "group": 9,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Meitnerium",
  "summary": "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is an extremely radioactive synthetic element (an element not found in nature that can be created in a laboratory). The most stable known isotope, meitnerium-278, has a half-life of 7.6 seconds.",
  "symbol": "Mt",
  "xpos": 9,
  "ypos": 7,
  "wxpos": 23,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 15, 2]
 },
 {
  "name": "Darmstadtium",
  "appearance": null,
  "atomic_mass": 281,
  "boil": null,
  "category": "transition metal",
  "number": 110,
  "period": 7,
  "group": 10,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Darmstadtium",
  "summary": "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is an extremely radioactive synthetic element. The most stable known isotope, darmstadtium-281, has a half-life of approximately 10 seconds.",
  "symbol": "Ds",
  "xpos": 10,
  "ypos": 7,
  "wxpos": 24,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 16, 2]
 },
 {
  "name": "Roentgenium",
  "appearance": null,
  "atomic_mass": 282,
  "boil": null,
  "category": "transition metal",
  "number": 111,
  "period": 7,
  "group": 11,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Roentgenium",
  "summary": "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is an extremely radioactive synthetic element (an element that can be created in a laboratory but is not found in nature); the most stable known isotope, roentgenium-282, has a half-life of 2.1 minutes. Roentgenium was first created in 1994 by the GSI Helmholtz Centre for Heavy Ion Research near Darmstadt, Germany.",
  "symbol": "Rg",
  "xpos": 11,
  "ypos": 7,
  "wxpos": 25,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 17, 2]
 },
 {
  "name": "Copernicium",
  "appearance": null,
  "atomic_mass": 285,
  "boil": 3570,
  "category": "transition metal",
  "number": 112,
  "period": 7,
  "group": 12,
  "phase": "Liquid",
  "source": "https://en.wikipedia.org/wiki/Copernicium",
  "summary": "Copernicium is a chemical element with symbol Cn and atomic number 112. It is an extremely radioactive synthetic element that can only be created in a laboratory. The most stable known isotope, copernicium-285, has a half-life of approximately 29 seconds, but it is possible that this copernicium isotope may have a nuclear isomer with a longer half-life, 8.9 min.",
  "symbol": "Cn",
  "xpos": 12,
  "ypos": 7,
  "wxpos": 26,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 18, 2]
 },
 {
  "name": "Nihonium",
  "appearance": null,
  "atomic_mass": 286,
  "boil": 1430,
  "category": "transition metal",
  "number": 113,
  "period": 7,
  "group": 13,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Ununtrium",
  "summary": "Nihonium is a chemical element with atomic number 113. It has a symbol Nh. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of 20 seconds.",
  "symbol": "Nh",
  "xpos": 13,
  "ypos": 7,
  "wxpos": 27,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 18, 3]
 },
 {
  "name": "Flerovium",
  "appearance": null,
  "atomic_mass": 289,
  "boil": 420,
  "category": "post-transition metal",
  "number": 114,
  "period": 7,
  "group": 14,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Flerovium",
  "summary": "Flerovium is a superheavy artificial chemical element with symbol Fl and atomic number 114. It is an extremely radioactive synthetic element. The element is named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia, where the element was discovered in 1998.",
  "symbol": "Fl",
  "xpos": 14,
  "ypos": 7,
  "wxpos": 28,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 18, 4]
 },
 {
  "name": "Moscovium",
  "appearance": null,
  "atomic_mass": 289,
  "boil": 1400,
  "category": "post-transition metal",
  "number": 115,
  "period": 7,
  "group": 15,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Ununpentium",
  "summary": "Moscovium is the name of a synthetic superheavy element in the periodic table that has the symbol Mc and has the atomic number 115. It is an extremely radioactive element; its most stable known isotope, moscovium-289, has a half-life of only 220 milliseconds. It is also known as eka-bismuth or simply element 115.",
  "symbol": "Mc",
  "xpos": 15,
  "ypos": 7,
  "wxpos": 29,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 18, 5]
 },
 {
  "name": "Livermorium",
  "appearance": null,
  "atomic_mass": 293,
  "boil": 1085,
  "category": "post-transition metal",
  "number": 116,
  "period": 7,
  "group": 16,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Livermorium",
  "summary": "Livermorium is a synthetic superheavy element with symbol Lv and atomic number 116. It is an extremely radioactive element that has only been created in the laboratory and has not been observed in nature. The element is named after the Lawrence Livermore National Laboratory in the United States, which collaborated with the Joint Institute for Nuclear Research in Dubna, Russia to discover livermorium in 2000.",
  "symbol": "Lv",
  "xpos": 16,
  "ypos": 7,
  "wxpos": 30,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 18, 6]
 },
 {
  "name": "Tennessine",
  "appearance": null,
  "atomic_mass": 294,
  "boil": 883,
  "category": "metalloid",
  "number": 117,
  "period": 7,
  "group": 17,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Tennessine",
  "summary": "Tennessine is a superheavy artificial chemical element with an atomic number of 117 and a symbol of Ts. Also known as eka-astatine or element 117, it is the second-heaviest known element and penultimate element of the 7th period of the periodic table. As of 2016, fifteen tennessine atoms have been observed: six when it was first synthesized in 2010, seven in 2012, and two in 2014.",
  "symbol": "Ts",
  "xpos": 17,
  "ypos": 7,
  "wxpos": 31,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 18, 7]
 },
 {
  "name": "Oganesson",
  "appearance": null,
  "atomic_mass": 294,
  "boil": 350,
  "category": "noble gas",
  "number": 118,
  "period": 7,
  "group": 18,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Oganesson",
  "summary": "Oganesson is IUPAC's name for the transactinide element with the atomic number 118 and element symbol Og. It is also known as eka-radon or element 118, and on the periodic table of the elements it is a p-block element and the last one of the 7th period. Oganesson is currently the only synthetic member of group 18.",
  "symbol": "Og",
  "xpos": 18,
  "ypos": 7,
  "wxpos": 32,
  "wypos": 7,
  "shells": [2, 8, 18, 32, 32, 18, 8]
 },
 {
  "name": "Ununennium",
  "appearance": null,
  "atomic_mass": 315,
  "boil": 630,
  "category": "alkali metal",
  "number": 119,
  "period": 8,
  "group": 1,
  "phase": "Solid",
  "source": "https://en.wikipedia.org/wiki/Ununennium",
  "summary": "Ununennium, also known as eka-francium or simply element 119, is the hypothetical chemical element with symbol Uue and atomic number 119. Ununennium and Uue are the temporary systematic IUPAC name and symbol respectively, until a permanent name is decided upon. In the periodic table of the elements, it is expected to be an s-block element, an alkali metal, and the first element in the eighth period.",
  "symbol": "Uue",
  "xpos": 1,
  "ypos": 8,
  "wxpos": 1,
  "wypos": 8,
  "shells": [2, 8, 18, 32, 32, 18, 8, 1]
 }
]
"""
